### ISSUE TITLE
NTP requires 123 UDP port

### ISSUE THREAD

**Issue by grm34** [grm34/archboot#194]
https://github.com/grm34/archboot/issues/141#issuecomment-621334200

**Comment by grm34** [comment]
Reported by @At1768 :

> I will open the port in my router tomorrow, perform an Install of Archboot and then report to the refered issue. I would like to check that before I write. Then I'll report in more detail. Because so far I have not yet performed an install with the port open (123 UDP).

**edit:** fixed by #200. NTP requires UDP 123 so archboot will now first check for this open port, otherwise only `timedatectl set-timezone _timezone_` will be applied.

**Comment by ghost** [comment]
@grm34 
This is a very good solution to the problem!

As indicated yesterday, I did the installation an hour ago with open port and everything worked great with ntp.

Couldn't answer you earlier due to time constraints. ;)

**Comment by grm34** [comment]
Yes, was head in code and did not get it! You're welcome ;)

**Comment by At1768** [comment]
@grm34 
please check out my **final** translation into german ;)
will of course be expanded in the future when there is something new to translate.
