### ISSUE TITLE
Custom partitioning

### ISSUE THREAD

**Issue by gromez** [grm34/archboot#20]
Hey grm34 :)

Archboot is designed for a clean install on a new disk.

Is it possible to set my own partitions and mount points, then run archboot? I looked at the code and it seems not.
Any solution for this case, or maybe I can just drop some stuff on [src/arch/partition](https://github.com/grm34/archboot/blob/master/src/arch/partition)

Thanks!

**Comment by ghost** [comment]
Having the ability to set SWAP / ROOT on 1 disk and /HOME on another during install would be much welcome.  Thank you.
-rk

**Comment by grm34** [comment]
Hi @gromez :)

You're right, no way to do this without dropping some stuff on [src/arch/partition](https://github.com/grm34/archboot/blob/master/src/arch/partition)

This will be implemented in next update, i do not have lot of time for this in summer.

@axeman48 same for you, i check this out

**Comment by grm34** [comment]
@gromez @axeman48 implemented in [dev](https://github.com/grm34/archboot/tree/dev) by [v2.8.1](https://github.com/grm34/archboot/commit/0f98c83dbd02ceda2a22342aa7e2e19322a8ac12), you can now select NO for fresh disk install and choose partitions you like.
`wget tiny.cc/archboot-dev; sh archboot-dev` for dev version
_**Don't forget to create and format required partitions before running archboot.**_

**Comment by PeterHindes** [comment]
It is annoying that I am forced to make a swap and home partition. I would like to be able to skip those partitions.

**Comment by grm34** [comment]
@PeterHindes Implemented in archboot-dev by 0daed98 refered in Partitioning 2.0
