### ISSUE TITLE
Doesn't work with nvme drives

### ISSUE THREAD

**Issue by talkelley3** [grm34/archboot#21]
Archboot does not recognize nvme0n1 etc. as a drive selection, only sda.  Is there any way you could update this in the near future?

**Comment by grm34** [comment]
@SuperTal3 sorry long time without internet. Yes right, not configured for nvme drives. I will update soon

**Comment by grm34** [comment]
Implemented in [dev](https://github.com/grm34/archboot/tree/dev) by [nvme drive support](https://github.com/grm34/archboot/commit/772e435dc951932bc2838bff0b4981de3166a0e9). I don't have any nvme drive for test so let me know. To download [dev](https://github.com/grm34/archboot/tree/dev) version use : `wget tiny.cc/archboot-dev; sh archboot-dev`
