### ISSUE TITLE
Mirrorlist Sorting

### ISSUE THREAD

**Issue by cynman** [grm34/archboot#26]
Jeremy,

Fantastic work here.  How hard would it be to drop in a routine to sort fastest mirror before installation?  Thank you for your time.

-rk

**Comment by grm34** [comment]
Hello @cynman

Thank you for your feedback.

Implemented in [dev](https://github.com/grm34/archboot/tree/dev) by [v2.8.3 Automatic mirrorlist sorting according user's country ](https://github.com/grm34/archboot/pull/27)
