### ISSUE TITLE
Implement locale choosing

### ISSUE THREAD

**Issue by benjaminfoo** [grm34/archboot#4]
Hello grm34, 

i really like this script as it allows me to automatically arch on some machines. The only downside is that the locale defaults to french (which is bad for me since im from germany - and I've never seen the french keyboard layout before) - so, do you have plans to do something like this?

**Comment by grm34** [comment]
Hello benjaminfoo, yes you're right, this will be implemented in next update.

**Comment by grm34** [comment]
@benjaminfoo implemented in v2.7.0 by https://github.com/grm34/archboot/pull/6
