### ISSUE TITLE
wget command downloading the redirect page

### ISSUE THREAD

**Issue by coyes** [grm34/archboot#5]
I need to use this: to get the scriptshell.

wget raw.githubusercontent.com/grm34/archboot/master/archboot; sh archboot

**Comment by grm34** [comment]
Hello, use shorten one instead `wget tiny.cc/archboot; sh archboot`
The right url is _**https://raw.githubusercontent.com/grm34/archboot/master/archboot**_

`wget https://raw.githubusercontent.com/grm34/archboot/master/archboot; sh archboot`
