### ISSUE TITLE
Stuck selecting home partition nvme0n1p10

### ISSUE THREAD

**Issue by PeterHindes** [grm34/archboot#59]
after using custom partitioning I have run into an error where the installer will not let me use nvme0n1p10 as a home partition.

**Comment by grm34** [comment]
try dev version by using [tiny.cc/archboot-dev](https://tiny.cc/archboot-dev)
it was just a condition to prevent user entries errors, [updated](https://github.com/grm34/archboot/pull/58) in dev (up to <10)

**Comment by PeterHindes** [comment]
Preventing user errors should be done with an echo and confirm.

**Comment by grm34** [comment]
> Preventing user errors should be done with an echo and confirm.

`until` much welcome in this case 

[commit](https://github.com/grm34/archboot/pull/58/commits/307d673d0c66399d6882da97bac8558be2404cfc)

please, use dev for requests

**Comment by PeterHindes** [comment]
Yes, unitl is quite nice for checking if what the user input is *valid*, but does nothing if they are say 1 number off when selecting a partition.

**Comment by grm34** [comment]
I use `_check()` function wich return cmd status when partitions mounted, anyway could be a nice way to check on user entry (`until` only prevent `trap` and `exit` errors (on user entry) and to have only 1 condition to handle :)

**Comment by grm34** [comment]
@PeterHindes see [commit](https://github.com/grm34/archboot/commit/9bec81ffe9c68540e32132c5f3923cf0ddd3765f).
We now check for existing drive id, no more regex matching.

**Comment by PeterHindes** [comment]
Cool, thats a good system.
