### ISSUE TITLE
HOME & SWAP partitions from REQUIRED to OPTIONAL 

### ISSUE THREAD

**Issue by PeterHindes** [grm34/archboot#61]
There seems to be no way to custom partition without a home partition or swap partition.

**Comment by grm34** [comment]
Right, for now archboot requires home and swap.

**Comment by PeterHindes** [comment]
Ok, thanks for the clarification. This is a pretty big con for me tbh.

**Comment by grm34** [comment]
You're welcome, it will be implemented i added enhancement label ;)

**Comment by PeterHindes** [comment]
nice

**Comment by grm34** [comment]
@PeterHindes Implemented in `archboot-dev` by [0daed98 ](https://github.com/grm34/archboot/pull/63/commits/1925286c26c2059ec4c46bb7c11277a89144469a) refered in [Partitioning 2.0](https://github.com/grm34/archboot/pull/63)
